[package]
name = "sitemap"
version = "0.3.0"
authors = ["Mikhail Svetov <svmk-tmsk@yandex.ru>", "tglman <https://github.com/tglman>", "John Boehr <jbboehr@gmail.com>", "Brady <https://github.com/BradyMcd>"]
description = "Sitemap parser (reader) and writer"
keywords=["sitemap","parser","reader","parse"]
readme="README.md"
documentation = "https://svmk.github.io/sitemap/0.3.0/sitemap/"
repository = "https://github.com/svmk/rust-sitemap"
license="MIT"
[dependencies]
xml-rs=">=0.3"
url="1.2"
chrono_utils="0.1.3"
chrono="^0.4"
